export const CHILD_MISSIONS = {
  'fase-1-abecedario': {
    slug: 'fase-1-abecedario', icono: '🔤', zona: 'COMUNICACIÓN CLARA', titulo: 'Deletrea y hazte entender',
    bajada: 'Reconoce las letras en inglés y deletrea nombres o palabras importantes.', color: '#b15f3b', suave: '#fff0e7', valor: 'Paciencia y comunicación respetuosa',
    historia: [
      { emoji: '🏫', texto: 'A new student joins the class.' },
      { emoji: '👋', texto: 'Hello! My name is Daniel.' },
      { emoji: '❓', texto: 'How do you spell your name?' },
      { emoji: '🔤', texto: 'D-A-N-I-E-L.' },
      { emoji: '😊', texto: 'Thank you. Now I can write it correctly.' },
    ],
    palabras: [
      { en: 'spell', es: 'deletrear', emoji: '🔤' }, { en: 'name', es: 'nombre', emoji: '🏷️' },
      { en: 'letter', es: 'letra', emoji: '✏️' }, { en: 'word', es: 'palabra', emoji: '💬' },
      { en: 'repeat', es: 'repetir', emoji: '🔁' }, { en: 'correctly', es: 'correctamente', emoji: '✅' },
    ],
    constructor: {
      inicios: ['Can you', 'Could you', 'Will you', 'Would you'],
      acciones: ['spell', 'repeat', 'say', 'write'],
      finales: ['your name?', 'that word?', 'the last letter?', 'my name.'],
    },
    retos: [
      { frase: 'How do you ___ your name?', correcta: 'spell', opciones: ['spell', 'count', 'draw'], ayuda: 'Spell significa deletrear.' },
      { frase: 'The word “book” begins with ___.', correcta: 'B', opciones: ['D', 'B', 'P'], ayuda: 'Book empieza con la letra B.' },
      { frase: 'Which letter comes after M?', correcta: 'N', opciones: ['L', 'O', 'N'], ayuda: 'En el alfabeto, N aparece después de M.' },
      { frase: 'D-A-N-I-E-L spells ___.', correcta: 'Daniel', opciones: ['David', 'Daniel', 'Diana'], ayuda: 'Une las letras en el mismo orden.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En clase', texto: 'Deletrear tu nombre en una presentación.' },
      { emoji: '📚', titulo: 'Al estudiar', texto: 'Confirmar cómo se escribe una palabra nueva.' },
      { emoji: '📞', titulo: 'En una llamada', texto: 'Aclarar nombres o datos sin confusiones.' },
    ],
  },
  'fase-1-numeros': {
    slug: 'fase-1-numeros', icono: '🔢', zona: 'NÚMEROS EN ACCIÓN', titulo: 'Cuenta, ordena y compara',
    bajada: 'Usa números cardinales para cantidades y ordinales para posiciones.', color: '#39766a', suave: '#e8f7f2', valor: 'Orden, esfuerzo y juego limpio',
    historia: [
      { emoji: '🏃', texto: 'Today our class has a friendly race.' },
      { emoji: '1️⃣', texto: 'Sofia finishes first.' },
      { emoji: '2️⃣', texto: 'Mateo finishes second.' },
      { emoji: '3️⃣', texto: 'Emma finishes third.' },
      { emoji: '👏', texto: 'There are twelve students, and everyone celebrates the effort.' },
    ],
    palabras: [
      { en: 'one', es: 'uno', emoji: '1️⃣' }, { en: 'twelve', es: 'doce', emoji: '🔢' },
      { en: 'first', es: 'primero', emoji: '🥇' }, { en: 'second', es: 'segundo', emoji: '🥈' },
      { en: 'third', es: 'tercero', emoji: '🥉' }, { en: 'how many', es: 'cuántos', emoji: '❓' },
    ],
    constructor: {
      inicios: ['In my class, there are', 'In the library, there are', 'At home, there are', 'In the park, there are'],
      acciones: ['twelve', 'fifteen', 'eighteen', 'twenty'],
      finales: ['books.', 'chairs.', 'plants.', 'people.'],
    },
    retos: [
      { frase: 'The number 12 is ___.', correcta: 'twelve', opciones: ['twenty', 'twelve', 'second'], ayuda: 'Twelve es doce; twenty es veinte.' },
      { frase: 'Position 1 is ___.', correcta: 'first', opciones: ['one', 'first', 'third'], ayuda: 'First indica la primera posición.' },
      { frase: 'Position 3 is ___.', correcta: 'third', opciones: ['three', 'second', 'third'], ayuda: 'Third indica la tercera posición.' },
      { frase: 'There are ___ days in a week.', correcta: 'seven', opciones: ['six', 'seven', 'eleven'], ayuda: 'Una semana tiene seven days.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'En la escuela', texto: 'Contar materiales y señalar posiciones.' },
      { emoji: '🏪', titulo: 'Al comprar', texto: 'Pedir cantidades y entender precios.' },
      { emoji: '🏅', titulo: 'En actividades', texto: 'Explicar resultados y turnos con respeto.' },
    ],
  },
  'fase-1-fecha': {
    slug: 'fase-1-fecha', icono: '📅', zona: 'ORGANIZA TU SEMANA', titulo: 'Fechas que importan',
    bajada: 'Expresa días, meses y fechas para organizar actividades importantes.', color: '#356f92', suave: '#e8f4fa', valor: 'Organización y responsabilidad',
    historia: [
      { emoji: '📋', texto: 'Our class is planning a science fair.' },
      { emoji: '📅', texto: 'The fair is on Friday, May tenth.' },
      { emoji: '🧪', texto: 'We prepare our project in April.' },
      { emoji: '⏰', texto: 'The final practice is at three o’clock.' },
      { emoji: '✅', texto: 'We write every date on the class calendar.' },
    ],
    palabras: [
      { en: 'today', es: 'hoy', emoji: '☀️' }, { en: 'tomorrow', es: 'mañana', emoji: '➡️' },
      { en: 'Monday', es: 'lunes', emoji: '📘' }, { en: 'Friday', es: 'viernes', emoji: '🎒' },
      { en: 'month', es: 'mes', emoji: '🗓️' }, { en: 'date', es: 'fecha', emoji: '📌' },
    ],
    constructor: {
      inicios: ['The activity is', 'The exam is', 'The game is', 'My birthday is'],
      acciones: ['on Monday,', 'on Friday,', 'on May tenth,', 'on June third,'],
      finales: ['this week.', 'next week.', 'this year.', 'as planned.'],
    },
    retos: [
      { frase: 'The class is ___ Monday.', correcta: 'on', opciones: ['at', 'on', 'in'], ayuda: 'Usamos on antes de un día específico.' },
      { frase: 'My birthday is ___ July.', correcta: 'in', opciones: ['on', 'at', 'in'], ayuda: 'Usamos in con meses.' },
      { frase: 'The day after Monday is ___.', correcta: 'Tuesday', opciones: ['Sunday', 'Tuesday', 'Friday'], ayuda: 'Tuesday es martes.' },
      { frase: 'December is a ___.', correcta: 'month', opciones: ['day', 'month', 'hour'], ayuda: 'December es un mes.' },
    ],
    aplicaciones: [
      { emoji: '📝', titulo: 'En la escuela', texto: 'Anotar exámenes, entregas y eventos.' },
      { emoji: '🎂', titulo: 'En familia', texto: 'Recordar cumpleaños y celebraciones.' },
      { emoji: '📅', titulo: 'Al organizarte', texto: 'Confirmar el día de una actividad.' },
    ],
  },
  'fase-1-hora': {
    slug: 'fase-1-hora', icono: '🕒', zona: 'TU DÍA A TIEMPO', titulo: '¿Qué hora es?',
    bajada: 'Pregunta y expresa la hora para seguir horarios y organizar tu día.', color: '#735b9b', suave: '#f2edfb', valor: 'Puntualidad y responsabilidad',
    historia: [
      { emoji: '⏰', texto: 'It is seven o’clock in the morning.' },
      { emoji: '🏫', texto: 'School starts at eight o’clock.' },
      { emoji: '🥪', texto: 'Lunch is at half past twelve.' },
      { emoji: '⚽', texto: 'Soccer practice is at a quarter past four.' },
      { emoji: '🌙', texto: 'I prepare my backpack before nine o’clock.' },
    ],
    palabras: [
      { en: 'o’clock', es: 'en punto', emoji: '🕐' }, { en: 'half past', es: 'y media', emoji: '🕧' },
      { en: 'quarter past', es: 'y cuarto', emoji: '🕒' }, { en: 'quarter to', es: 'menos cuarto', emoji: '🕘' },
      { en: 'morning', es: 'mañana', emoji: '🌅' }, { en: 'night', es: 'noche', emoji: '🌙' },
    ],
    constructor: {
      inicios: ['My class starts', 'Lunch begins', 'Practice starts', 'My day begins'],
      acciones: ['at seven', 'at eight', 'at half past twelve', 'at a quarter past four'],
      finales: ['in the morning.', 'every day.', 'on time.', 'as planned.'],
    },
    retos: [
      { frase: '7:00 is seven ___.', correcta: 'o’clock', opciones: ['past', 'o’clock', 'half'], ayuda: 'Para una hora exacta usamos o’clock.' },
      { frase: '3:30 is half ___ three.', correcta: 'past', opciones: ['to', 'past', 'at'], ayuda: 'Half past indica treinta minutos después.' },
      { frase: 'School starts ___ eight.', correcta: 'at', opciones: ['on', 'in', 'at'], ayuda: 'Usamos at antes de una hora.' },
      { frase: '8:45 is a quarter ___ nine.', correcta: 'to', opciones: ['past', 'to', 'on'], ayuda: 'Faltan quince minutos para las nueve.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Entender horarios de clases y descansos.' },
      { emoji: '⚽', titulo: 'En actividades', texto: 'Llegar puntualmente a prácticas o reuniones.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Organizar tareas, comidas y descanso.' },
    ],
  },
  'fase-1-saludos': {
    slug: 'fase-1-saludos', icono: '👋', zona: 'BUENAS CONVERSACIONES', titulo: 'Saluda con confianza',
    bajada: 'Elige un saludo o una despedida según el momento y la situación.', color: '#b06b33', suave: '#fff3e4', valor: 'Amabilidad y respeto',
    historia: [
      { emoji: '🌅', texto: 'Good morning, Ms. Green.' },
      { emoji: '👩‍🏫', texto: 'Good morning, Lucas. How are you?' },
      { emoji: '😊', texto: 'I am fine, thank you.' },
      { emoji: '👋', texto: 'Hi, Emma! Are you ready for class?' },
      { emoji: '🎒', texto: 'Yes! See you in the classroom.' },
    ],
    palabras: [
      { en: 'hello', es: 'hola', emoji: '👋' }, { en: 'good morning', es: 'buenos días', emoji: '🌅' },
      { en: 'how are you?', es: '¿cómo estás?', emoji: '🙂' }, { en: 'thank you', es: 'gracias', emoji: '🙏' },
      { en: 'see you', es: 'nos vemos', emoji: '➡️' }, { en: 'goodbye', es: 'adiós', emoji: '🎒' },
    ],
    constructor: {
      inicios: ['Good morning,', 'Hello,', 'Hi,', 'Good afternoon,'],
      acciones: ['Emma.', 'Lucas.', 'everyone.', 'my friend.'],
      finales: ['How are you?', 'Nice to see you.', 'Have a good day.', 'Are you ready?'],
    },
    retos: [
      { frase: 'At 8:00 a.m. we say ___.', correcta: 'Good morning', opciones: ['Good night', 'Good morning', 'Goodbye'], ayuda: 'Good morning se usa durante la mañana.' },
      { frase: 'A neutral way to say hola is ___.', correcta: 'Hello', opciones: ['Goodbye', 'Hello', 'See you'], ayuda: 'Hello funciona en muchas situaciones.' },
      { frase: 'To ask ¿cómo estás? say ___.', correcta: 'How are you?', opciones: ['Who are you?', 'How are you?', 'Where are you?'], ayuda: 'How are you? pregunta cómo está alguien.' },
      { frase: 'A friendly farewell is ___.', correcta: 'See you', opciones: ['Thank you', 'Good morning', 'See you'], ayuda: 'See you significa nos vemos.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Saludar a docentes y compañeros con respeto.' },
      { emoji: '🏠', titulo: 'En familia', texto: 'Iniciar y cerrar conversaciones amables.' },
      { emoji: '🤝', titulo: 'Al conocer a alguien', texto: 'Dar una primera impresión cordial.' },
    ],
  },
  'fase-1-abreviaturas': {
    slug: 'fase-1-abreviaturas', icono: '💬', zona: 'PALABRAS COTIDIANAS', titulo: 'Mensajes cortos y claros',
    bajada: 'Reconoce abreviaturas comunes sin perder claridad ni respeto al escribir.', color: '#39766a', suave: '#e8f7f2', valor: 'Claridad y uso responsable de mensajes',
    historia: [
      { emoji: '🔬', texto: 'Our science group needs information for a project.' },
      { emoji: '📱', texto: 'Sara writes: “FYI, the project is due on Friday.”' },
      { emoji: '📷', texto: 'Leo adds a photo from the science book.' },
      { emoji: 'ℹ️', texto: 'The school app has more info.' },
      { emoji: '✅', texto: 'Everyone understands the short and clear message.' },
    ],
    palabras: [
      { en: 'info', es: 'información', emoji: 'ℹ️' }, { en: 'app', es: 'aplicación', emoji: '📱' },
      { en: 'photo', es: 'fotografía', emoji: '📷' }, { en: 'TV', es: 'televisión', emoji: '📺' },
      { en: 'FYI', es: 'para tu información', emoji: '💡' }, { en: 'ASAP', es: 'lo antes posible', emoji: '⏱️' },
    ],
    constructor: {
      inicios: ['Please send', 'Please share', 'Please check', 'Please review'],
      acciones: ['the info', 'the photo', 'the app', 'the message'],
      finales: ['for our project.', 'with the group.', 'before class.', 'when you have time.'],
    },
    retos: [
      { frase: 'The short form of information is ___.', correcta: 'info', opciones: ['info', 'photo', 'TV'], ayuda: 'Info es una forma cotidiana de information.' },
      { frase: 'The short form of application is ___.', correcta: 'app', opciones: ['ASAP', 'app', 'FYI'], ayuda: 'App es la forma corta de application.' },
      { frase: '___ means “para tu información”.', correcta: 'FYI', opciones: ['TV', 'ASAP', 'FYI'], ayuda: 'FYI significa for your information.' },
      { frase: 'A picture taken with a camera is a ___.', correcta: 'photo', opciones: ['photo', 'fridge', 'app'], ayuda: 'Photo es la forma cotidiana de photograph.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'En proyectos', texto: 'Compartir información de forma breve y clara.' },
      { emoji: '📱', titulo: 'En aplicaciones', texto: 'Comprender botones y mensajes frecuentes.' },
      { emoji: '💬', titulo: 'En mensajes', texto: 'Usar formas cortas sin escribir con descuido.' },
    ],
  },
  'fase-1-frutas': {
    slug: 'fase-1-frutas', icono: '🍎', zona: 'ELECCIONES SALUDABLES', titulo: 'Frutas para compartir',
    bajada: 'Nombra frutas, expresa preferencias y pide alimentos con amabilidad.', color: '#b15f3b', suave: '#fff0e7', valor: 'Gratitud, salud y convivencia',
    historia: [
      { emoji: '🧺', texto: 'Our class prepares a fruit picnic.' },
      { emoji: '🍎', texto: 'Mia brings apples and bananas.' },
      { emoji: '🍊', texto: 'Daniel brings oranges and grapes.' },
      { emoji: '🍉', texto: 'My favorite fruit is watermelon.' },
      { emoji: '🤝', texto: 'We wash the fruit and share it with everyone.' },
    ],
    palabras: [
      { en: 'apple', es: 'manzana', emoji: '🍎' }, { en: 'banana', es: 'plátano', emoji: '🍌' },
      { en: 'orange', es: 'naranja', emoji: '🍊' }, { en: 'grapes', es: 'uvas', emoji: '🍇' },
      { en: 'watermelon', es: 'sandía', emoji: '🍉' }, { en: 'strawberry', es: 'fresa', emoji: '🍓' },
    ],
    constructor: {
      inicios: ['For lunch, I', 'At home, we', 'At the picnic, I', 'Today, I'],
      acciones: ['would like', 'will share', 'will choose', 'want'],
      finales: ['an apple.', 'a banana.', 'some grapes.', 'a strawberry.'],
    },
    retos: [
      { frase: '🍎 is an ___.', correcta: 'apple', opciones: ['orange', 'apple', 'grape'], ayuda: 'Apple significa manzana.' },
      { frase: '🍉 is a ___.', correcta: 'watermelon', opciones: ['strawberry', 'banana', 'watermelon'], ayuda: 'Watermelon significa sandía.' },
      { frase: 'I would like ___ orange.', correcta: 'an', opciones: ['a', 'an', 'some'], ayuda: 'Usamos an antes del sonido vocal de orange.' },
      { frase: 'We wash fruit before we ___ it.', correcta: 'eat', opciones: ['eat', 'draw', 'spell'], ayuda: 'Lavar la fruta antes de comerla es un hábito saludable.' },
    ],
    aplicaciones: [
      { emoji: '🥪', titulo: 'En el almuerzo', texto: 'Nombrar lo que llevas y expresar preferencias.' },
      { emoji: '🛒', titulo: 'Al comprar', texto: 'Pedir fruta y comprender cantidades sencillas.' },
      { emoji: '🏠', titulo: 'En familia', texto: 'Elegir, lavar y compartir alimentos saludables.' },
    ],
  },
  'fase-1-familia-coloquial': {
    slug: 'fase-1-familia-coloquial', icono: '🏡', zona: 'FAMILIA Y VIDA COTIDIANA', titulo: 'Mi familia y mi hogar',
    bajada: 'Aprende a presentar a tu familia y contar cómo colaboran en casa.', color: '#3478e5', suave: '#e8f2ff', valor: 'Amor, respeto y colaboración',
    historia: [
      { emoji: '👧', texto: 'My name is Mia. I live with my mom, my dad, and my brother Leo.' },
      { emoji: '📚', texto: 'My mom helps me with my homework.' },
      { emoji: '🥞', texto: 'My dad makes breakfast on Sunday.' },
      { emoji: '🧹', texto: 'Leo and I clean our room together.' },
      { emoji: '❤️', texto: 'We love, respect, and help each other.' },
    ],
    palabras: [
      { en: 'mom', es: 'mamá', emoji: '👩' }, { en: 'dad', es: 'papá', emoji: '👨' },
      { en: 'brother', es: 'hermano', emoji: '👦' }, { en: 'sister', es: 'hermana', emoji: '👧' },
      { en: 'grandparents', es: 'abuelos', emoji: '👵👴' }, { en: 'family', es: 'familia', emoji: '🏡' },
    ],
    constructor: {
      inicios: ['My brother and I', 'My parents and I', 'My family and I', 'We'],
      acciones: ['help', 'respect', 'love', 'listen to'],
      finales: ['one another.', 'our parents.', 'our grandparents.', 'our family.'],
    },
    retos: [
      { frase: 'My mother is my ___.', correcta: 'mom', opciones: ['mom', 'sister', 'grandma'], ayuda: 'Mom significa mamá.' },
      { frase: 'My father is my ___.', correcta: 'dad', opciones: ['brother', 'dad', 'grandpa'], ayuda: 'Dad significa papá.' },
      { frase: 'My brother and I ___ our room.', correcta: 'clean', opciones: ['cleans', 'clean', 'cleaning'], ayuda: 'Con “My brother and I” usamos clean.' },
      { frase: 'We help ___ other at home.', correcta: 'each', opciones: ['each', 'every', 'one'], ayuda: 'Each other significa mutuamente.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Presentar a tu familia en clase.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Contar cómo colaboran y se respetan.' },
      { emoji: '💬', titulo: 'En conversación', texto: 'Hablar de padres, hermanos y abuelos.' },
    ],
  },
  'fase-2-to-be-afirmativo': {
    slug: 'fase-2-to-be-afirmativo', icono: '✨', zona: 'QUIÉN SOY Y CÓMO ESTOY', titulo: 'Soy, eres, somos',
    bajada: 'Usa am, is y are para presentarte y describir personas o situaciones.', color: '#356f92', suave: '#e8f4fa', valor: 'Confianza y respeto por los demás',
    historia: [
      { emoji: '🏫', texto: 'I am a new student in this class.' },
      { emoji: '😊', texto: 'My teacher is kind and patient.' },
      { emoji: '👥', texto: 'My classmates are friendly.' },
      { emoji: '📚', texto: 'We are ready to learn together.' },
      { emoji: '⭐', texto: 'English is a new challenge, and I am excited.' },
    ],
    palabras: [
      { en: 'I am', es: 'yo soy/estoy', emoji: '🙋' }, { en: 'you are', es: 'tú eres/estás', emoji: '👉' },
      { en: 'he is', es: 'él es/está', emoji: '👦' }, { en: 'she is', es: 'ella es/está', emoji: '👧' },
      { en: 'we are', es: 'nosotros somos/estamos', emoji: '👥' }, { en: 'they are', es: 'ellos son/están', emoji: '🧑‍🤝‍🧑' },
    ],
    constructor: {
      inicios: ['I am', 'You are', 'He is', 'She is'],
      acciones: ['ready to', 'happy to', 'excited to', 'proud to'],
      finales: ['learn English.', 'help the class.', 'start the project.', 'do my best.'],
    },
    retos: [
      { frase: 'I ___ ready.', correcta: 'am', opciones: ['is', 'am', 'are'], ayuda: 'Con I usamos am.' },
      { frase: 'She ___ my classmate.', correcta: 'is', opciones: ['am', 'are', 'is'], ayuda: 'Con she usamos is.' },
      { frase: 'We ___ a team.', correcta: 'are', opciones: ['are', 'is', 'am'], ayuda: 'Con we usamos are.' },
      { frase: 'My parents ___ at home.', correcta: 'are', opciones: ['is', 'am', 'are'], ayuda: 'Parents es plural, por eso usamos are.' },
    ],
    aplicaciones: [
      { emoji: '🙋', titulo: 'Al presentarte', texto: 'Decir quién eres y cómo te sientes.' },
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Describir compañeros, materias y lugares.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Contar dónde están tus familiares.' },
    ],
  },
  'fase-2-pronombres-sujeto-objeto': {
    slug: 'fase-2-pronombres-sujeto-objeto', icono: '👥', zona: 'PERSONAS EN LA ORACIÓN', titulo: 'Quién actúa y quién recibe',
    bajada: 'Distingue pronombres de sujeto y objeto para evitar repeticiones.', color: '#735b9b', suave: '#f2edfb', valor: 'Escucha, cooperación y respeto',
    historia: [
      { emoji: '👩‍🏫', texto: 'Ms. Green gives us a class project.' },
      { emoji: '👧', texto: 'Sofia has a good idea. She shares it with us.' },
      { emoji: '👦', texto: 'Daniel draws the poster. We help him.' },
      { emoji: '👥', texto: 'Our classmates listen to us.' },
      { emoji: '✅', texto: 'We finish the project, and our teacher congratulates us.' },
    ],
    palabras: [
      { en: 'I / me', es: 'yo / me', emoji: '🙋' }, { en: 'you / you', es: 'tú / te', emoji: '👉' },
      { en: 'he / him', es: 'él / lo-le', emoji: '👦' }, { en: 'she / her', es: 'ella / la-le', emoji: '👧' },
      { en: 'we / us', es: 'nosotros / nos', emoji: '👥' }, { en: 'they / them', es: 'ellos / los-les', emoji: '🧑‍🤝‍🧑' },
    ],
    constructor: {
      inicios: ['Our teacher', 'My mom', 'My friend', 'My brother'],
      acciones: ['helps', 'encourages', 'invites', 'listens to'],
      finales: ['me.', 'him.', 'her.', 'us.'],
    },
    retos: [
      { frase: 'Sofia is my friend. ___ is kind.', correcta: 'She', opciones: ['Her', 'She', 'Him'], ayuda: 'She realiza la acción y funciona como sujeto.' },
      { frase: 'Daniel needs help. We help ___.', correcta: 'him', opciones: ['he', 'him', 'they'], ayuda: 'Him recibe la acción.' },
      { frase: 'My friends call ___.', correcta: 'me', opciones: ['I', 'me', 'we'], ayuda: 'Después del verbo usamos el pronombre objeto me.' },
      { frase: 'Emma and I study together. ___ are classmates.', correcta: 'We', opciones: ['Us', 'They', 'We'], ayuda: 'Emma and I se reemplaza por We.' },
    ],
    aplicaciones: [
      { emoji: '📝', titulo: 'Al escribir', texto: 'Evitar repetir nombres en cada oración.' },
      { emoji: '💬', titulo: 'Al conversar', texto: 'Explicar claramente quién hace algo.' },
      { emoji: '🤝', titulo: 'En equipo', texto: 'Contar quién ayuda o escucha a otra persona.' },
    ],
  },
  'fase-3-presente-simple': {
    slug: 'fase-3-presente-simple', icono: '☀️', zona: 'HÁBITOS QUE CONSTRUYEN', titulo: 'Mi rutina diaria',
    bajada: 'Usa el presente simple para hablar de hábitos, gustos y actividades frecuentes.', color: '#b06b33', suave: '#fff3e4', valor: 'Constancia y buenos hábitos',
    historia: [
      { emoji: '🌅', texto: 'I wake up early on school days.' },
      { emoji: '🥣', texto: 'I eat breakfast with my family.' },
      { emoji: '🏫', texto: 'My sister walks to school with me.' },
      { emoji: '📚', texto: 'We do our homework in the afternoon.' },
      { emoji: '🌙', texto: 'I prepare my backpack before I sleep.' },
    ],
    palabras: [
      { en: 'wake up', es: 'despertarse', emoji: '⏰' }, { en: 'eat breakfast', es: 'desayunar', emoji: '🥣' },
      { en: 'go to school', es: 'ir a la escuela', emoji: '🏫' }, { en: 'study', es: 'estudiar', emoji: '📚' },
      { en: 'help', es: 'ayudar', emoji: '🤝' }, { en: 'every day', es: 'cada día', emoji: '📅' },
    ],
    constructor: {
      inicios: ['Every day, I', 'After school, we', 'On weekdays, I', 'At home, we'],
      acciones: ['practice', 'read', 'help with', 'prepare'],
      finales: ['English.', 'a good book.', 'our chores.', 'our schoolwork.'],
    },
    retos: [
      { frase: 'I ___ English every day.', correcta: 'study', opciones: ['studies', 'study', 'studying'], ayuda: 'Con I usamos el verbo base: study.' },
      { frase: 'She ___ to school at eight.', correcta: 'goes', opciones: ['go', 'going', 'goes'], ayuda: 'Con she agregamos -s o -es.' },
      { frase: 'We ___ our parents at home.', correcta: 'help', opciones: ['helps', 'help', 'helping'], ayuda: 'Con we usamos help sin -s.' },
      { frase: 'He ___ breakfast with his family.', correcta: 'eats', opciones: ['eat', 'eats', 'eating'], ayuda: 'Con he usamos eats.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'En la escuela', texto: 'Describir materias y hábitos de estudio.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Contar tu rutina y cómo colaboras.' },
      { emoji: '⚽', titulo: 'En tu tiempo libre', texto: 'Hablar de actividades que haces seguido.' },
    ],
  },
  'fase-3-presente-continuo': {
    slug: 'fase-3-presente-continuo', icono: '🎬', zona: 'ACCIONES EN MOVIMIENTO', titulo: 'Lo que está pasando ahora',
    bajada: 'Usa am, is o are más -ing para describir acciones en progreso.', color: '#39766a', suave: '#e8f7f2', valor: 'Atención y participación',
    historia: [
      { emoji: '🏫', texto: 'Our class is preparing an environment project.' },
      { emoji: '✍️', texto: 'I am writing the introduction.' },
      { emoji: '🎨', texto: 'Sofia is drawing a clean park.' },
      { emoji: '♻️', texto: 'Daniel and Leo are building a recycling box.' },
      { emoji: '🤝', texto: 'We are working together right now.' },
    ],
    palabras: [
      { en: 'right now', es: 'ahora mismo', emoji: '⏱️' }, { en: 'writing', es: 'escribiendo', emoji: '✍️' },
      { en: 'reading', es: 'leyendo', emoji: '📖' }, { en: 'drawing', es: 'dibujando', emoji: '🎨' },
      { en: 'building', es: 'construyendo', emoji: '🧱' }, { en: 'working', es: 'trabajando', emoji: '🛠️' },
    ],
    constructor: {
      inicios: ['Right now, I am', 'At the moment, we are', 'Today, they are', 'Look! She is'],
      acciones: ['reading', 'writing', 'building', 'preparing'],
      finales: ['a school project.', 'a new story.', 'a helpful poster.', 'an activity.'],
    },
    retos: [
      { frase: 'I am ___ a book now.', correcta: 'reading', opciones: ['read', 'reads', 'reading'], ayuda: 'Después de am usamos el verbo con -ing.' },
      { frase: 'She ___ drawing a poster.', correcta: 'is', opciones: ['am', 'is', 'are'], ayuda: 'Con she usamos is.' },
      { frase: 'They are ___ together.', correcta: 'working', opciones: ['work', 'works', 'working'], ayuda: 'Are + working expresa una acción en progreso.' },
      { frase: 'We ___ preparing the project.', correcta: 'are', opciones: ['is', 'are', 'am'], ayuda: 'Con we usamos are.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En clase', texto: 'Contar qué está haciendo el grupo ahora.' },
      { emoji: '📞', titulo: 'En una llamada', texto: 'Explicar qué haces en este momento.' },
      { emoji: '🖼️', titulo: 'Al describir', texto: 'Narrar las acciones visibles en una imagen.' },
    ],
  },
  'fase-3-simple-vs-continuo': {
    slug: 'fase-3-simple-vs-continuo', icono: '🔎', zona: 'RUTINA O MOMENTO', titulo: 'Cada día o justo ahora',
    bajada: 'Compara hábitos frecuentes con acciones que están ocurriendo en este momento.', color: '#735b9b', suave: '#f2edfb', valor: 'Observación y pensamiento claro',
    historia: [
      { emoji: '📚', texto: 'I usually study in the library after school.' },
      { emoji: '🏠', texto: 'Today I am studying at home.' },
      { emoji: '⚽', texto: 'My brother plays soccer every Saturday.' },
      { emoji: '🌧️', texto: 'It is raining now, so he is reading a book.' },
      { emoji: '🧠', texto: 'Time words help us choose the correct present tense.' },
    ],
    palabras: [
      { en: 'usually', es: 'normalmente', emoji: '🔁' }, { en: 'every day', es: 'cada día', emoji: '📅' },
      { en: 'right now', es: 'ahora mismo', emoji: '⏱️' }, { en: 'today', es: 'hoy', emoji: '☀️' },
      { en: 'routine', es: 'rutina', emoji: '🔄' }, { en: 'in progress', es: 'en progreso', emoji: '🎬' },
    ],
    constructor: {
      inicios: ['I compare', 'I read', 'I check', 'I explain'],
      acciones: ['the time marker in', 'the verb form in', 'the meaning of', 'the situation in'],
      finales: ['“I study every day.”', '“I am studying now.”', '“She plays on Mondays.”', '“She is playing today.”'],
    },
    retos: [
      { frase: 'I ___ English every day.', correcta: 'study', opciones: ['study', 'am studying', 'studies'], ayuda: 'Every day indica una rutina: presente simple.' },
      { frase: 'I ___ English right now.', correcta: 'am studying', opciones: ['study', 'am studying', 'studies'], ayuda: 'Right now indica una acción en progreso.' },
      { frase: 'She usually ___ to school.', correcta: 'walks', opciones: ['walks', 'is walking', 'walk'], ayuda: 'Usually señala un hábito y she requiere walks.' },
      { frase: 'Look! They ___ soccer.', correcta: 'are playing', opciones: ['play', 'plays', 'are playing'], ayuda: 'Look! señala algo que ocurre en este momento.' },
    ],
    aplicaciones: [
      { emoji: '🗓️', titulo: 'Al hablar de rutinas', texto: 'Explicar lo que haces habitualmente.' },
      { emoji: '📸', titulo: 'Al describir el momento', texto: 'Contar qué está ocurriendo ahora.' },
      { emoji: '📝', titulo: 'Al escribir historias', texto: 'Diferenciar contexto habitual y escena actual.' },
    ],
  },
  'fase-4-was-were': {
    slug: 'fase-4-was-were', icono: '🕰️', zona: 'RECUERDOS Y EXPERIENCIAS', titulo: 'Así era y así estaba',
    bajada: 'Usa was y were para describir personas, lugares y situaciones del pasado.', color: '#356f92', suave: '#e8f4fa', valor: 'Gratitud por lo aprendido',
    historia: [
      { emoji: '🚌', texto: 'Yesterday our class was on a school trip.' },
      { emoji: '🌳', texto: 'The park was clean and beautiful.' },
      { emoji: '👥', texto: 'We were excited about the activities.' },
      { emoji: '🧑‍🏫', texto: 'Our teachers were patient and helpful.' },
      { emoji: '😊', texto: 'I was tired at the end, but I was happy.' },
    ],
    palabras: [
      { en: 'yesterday', es: 'ayer', emoji: '⬅️' }, { en: 'was', es: 'era/estaba', emoji: '1️⃣' },
      { en: 'were', es: 'eran/estaban', emoji: '👥' }, { en: 'excited', es: 'emocionado', emoji: '⭐' },
      { en: 'tired', es: 'cansado', emoji: '😴' }, { en: 'helpful', es: 'servicial', emoji: '🤝' },
    ],
    constructor: {
      inicios: ['Yesterday, I was', 'Last Saturday, we were', 'After class, she was', 'In the morning, they were'],
      acciones: ['ready for', 'happy about', 'excited about', 'responsible for'],
      finales: ['the activity.', 'the project.', 'the family visit.', 'the clean-up.'],
    },
    retos: [
      { frase: 'I ___ at school yesterday.', correcta: 'was', opciones: ['am', 'was', 'were'], ayuda: 'Con I en pasado usamos was.' },
      { frase: 'We ___ ready for the trip.', correcta: 'were', opciones: ['was', 'are', 'were'], ayuda: 'Con we en pasado usamos were.' },
      { frase: 'The park ___ beautiful.', correcta: 'was', opciones: ['were', 'was', 'is'], ayuda: 'Park es singular, por eso usamos was.' },
      { frase: 'My parents ___ at home.', correcta: 'were', opciones: ['was', 'were', 'are'], ayuda: 'Parents es plural, por eso usamos were.' },
    ],
    aplicaciones: [
      { emoji: '📸', titulo: 'Al recordar', texto: 'Describir cómo era un lugar o momento.' },
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Contar dónde estaban personas u objetos.' },
      { emoji: '🏠', titulo: 'En familia', texto: 'Compartir recuerdos y experiencias pasadas.' },
    ],
  },
  'fase-4-pasado-simple': {
    slug: 'fase-4-pasado-simple', icono: '📖', zona: 'HISTORIAS QUE YA OCURRIERON', titulo: 'Lo que hice ayer',
    bajada: 'Usa el pasado simple para contar acciones terminadas y ordenar una experiencia.', color: '#b06b33', suave: '#fff3e4', valor: 'Responsabilidad y reflexión',
    historia: [
      { emoji: '🌱', texto: 'Last Saturday, my family worked in our garden.' },
      { emoji: '🧤', texto: 'My dad prepared the tools.' },
      { emoji: '💧', texto: 'My mom watered the plants.' },
      { emoji: '🌼', texto: 'My brother and I planted new flowers.' },
      { emoji: '♻️', texto: 'We cleaned the area and recycled the empty containers.' },
    ],
    palabras: [
      { en: 'worked', es: 'trabajó/trabajaron', emoji: '🛠️' }, { en: 'prepared', es: 'preparó', emoji: '🧤' },
      { en: 'watered', es: 'regó', emoji: '💧' }, { en: 'planted', es: 'plantó', emoji: '🌱' },
      { en: 'cleaned', es: 'limpió', emoji: '🧹' }, { en: 'recycled', es: 'recicló', emoji: '♻️' },
    ],
    constructor: {
      inicios: ['Yesterday, I', 'Last week, we', 'On Saturday, I', 'After class, we'],
      acciones: ['worked on', 'talked about', 'helped with', 'prepared for'],
      finales: ['the project.', 'our homework.', 'the garden.', 'a family activity.'],
    },
    retos: [
      { frase: 'Yesterday I ___ my homework.', correcta: 'finished', opciones: ['finish', 'finished', 'finishing'], ayuda: 'Una acción terminada usa el pasado: finished.' },
      { frase: 'We ___ flowers on Saturday.', correcta: 'planted', opciones: ['plant', 'planted', 'plants'], ayuda: 'Plant es regular: plant + ed.' },
      { frase: 'She ___ the tools for us.', correcta: 'prepared', opciones: ['prepares', 'prepared', 'prepare'], ayuda: 'Prepared indica una acción terminada.' },
      { frase: 'They ___ the area after the activity.', correcta: 'cleaned', opciones: ['cleaning', 'clean', 'cleaned'], ayuda: 'Cleaned es el pasado de clean.' },
    ],
    aplicaciones: [
      { emoji: '📔', titulo: 'En un diario', texto: 'Escribir lo que hiciste durante el día.' },
      { emoji: '🏫', titulo: 'En clase', texto: 'Relatar una actividad o proyecto terminado.' },
      { emoji: '👨‍👩‍👧‍👦', titulo: 'En familia', texto: 'Compartir experiencias y buenos recuerdos.' },
    ],
  },
  'fase-4-pasado-continuo': {
    slug: 'fase-4-pasado-continuo', icono: '🎞️', zona: 'UNA ESCENA DEL PASADO', titulo: 'Lo que estaba ocurriendo',
    bajada: 'Usa was o were más -ing para describir una acción que estaba en progreso.', color: '#735b9b', suave: '#f2edfb', valor: 'Atención y comprensión de los hechos',
    historia: [
      { emoji: '🌧️', texto: 'It was raining yesterday afternoon.' },
      { emoji: '📖', texto: 'I was reading in the living room.' },
      { emoji: '🍲', texto: 'My mom was preparing dinner.' },
      { emoji: '🧩', texto: 'My dad and my brother were completing a puzzle.' },
      { emoji: '💡', texto: 'We were spending time together when the lights went out.' },
    ],
    palabras: [
      { en: 'was reading', es: 'estaba leyendo', emoji: '📖' }, { en: 'were playing', es: 'estaban jugando', emoji: '🧩' },
      { en: 'was raining', es: 'estaba lloviendo', emoji: '🌧️' }, { en: 'when', es: 'cuando', emoji: '⚡' },
      { en: 'while', es: 'mientras', emoji: '↔️' }, { en: 'at that moment', es: 'en ese momento', emoji: '🕰️' },
    ],
    constructor: {
      inicios: ['I was', 'We were', 'She was', 'They were'],
      acciones: ['reading quietly', 'working together', 'preparing dinner', 'doing homework'],
      finales: ['when it started to rain.', 'when the phone rang.', 'at that moment.', 'while music was playing.'],
    },
    retos: [
      { frase: 'I ___ reading when you called.', correcta: 'was', opciones: ['am', 'was', 'were'], ayuda: 'Con I en pasado continuo usamos was.' },
      { frase: 'They were ___ a puzzle.', correcta: 'completing', opciones: ['complete', 'completed', 'completing'], ayuda: 'Después de were usamos el verbo con -ing.' },
      { frase: 'She ___ preparing dinner.', correcta: 'was', opciones: ['were', 'was', 'is'], ayuda: 'Con she usamos was.' },
      { frase: 'We were studying ___ the lights went out.', correcta: 'when', opciones: ['every day', 'when', 'tomorrow'], ayuda: 'When introduce el hecho que interrumpe la escena.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'Al contar historias', texto: 'Describir el fondo de una escena pasada.' },
      { emoji: '💬', titulo: 'En conversación', texto: 'Explicar qué hacías cuando ocurrió algo.' },
      { emoji: '🖼️', titulo: 'Al observar imágenes', texto: 'Imaginar acciones que estaban en progreso.' },
    ],
  },
  'fase-5-perfecto-intro': {
    slug: 'fase-5-perfecto-intro', icono: '🌉', zona: 'EXPERIENCIAS QUE CUENTAN', titulo: 'Lo que hemos logrado',
    bajada: 'Conecta una experiencia pasada con el presente usando have o has.', color: '#39766a', suave: '#e8f7f2', valor: 'Reconocer el esfuerzo y el aprendizaje',
    historia: [
      { emoji: '🌎', texto: 'Our class has completed an environment project.' },
      { emoji: '♻️', texto: 'We have learned how to reuse paper.' },
      { emoji: '🌱', texto: 'Sofia has planted a tree at school.' },
      { emoji: '💧', texto: 'Daniel has created a poster about saving water.' },
      { emoji: '⭐', texto: 'We have made a positive difference together.' },
    ],
    palabras: [
      { en: 'have learned', es: 'hemos aprendido', emoji: '📚' }, { en: 'has created', es: 'ha creado', emoji: '🎨' },
      { en: 'have completed', es: 'hemos completado', emoji: '✅' }, { en: 'has planted', es: 'ha plantado', emoji: '🌱' },
      { en: 'experience', es: 'experiencia', emoji: '🧭' }, { en: 'result', es: 'resultado', emoji: '⭐' },
    ],
    constructor: {
      inicios: ['I have', 'We have', 'She has', 'He has'],
      acciones: ['worked on', 'learned about', 'participated in', 'contributed to'],
      finales: ['a school project.', 'our community.', 'the environment.', 'a family activity.'],
    },
    retos: [
      { frase: 'I ___ completed my homework.', correcta: 'have', opciones: ['has', 'have', 'did'], ayuda: 'Con I usamos have.' },
      { frase: 'She ___ planted a tree.', correcta: 'has', opciones: ['have', 'is', 'has'], ayuda: 'Con she usamos has.' },
      { frase: 'We have ___ a difference.', correcta: 'made', opciones: ['make', 'made', 'making'], ayuda: 'El participio de make es made.' },
      { frase: 'He has ___ the project.', correcta: 'finished', opciones: ['finish', 'finished', 'finishing'], ayuda: 'Has + finished forma el presente perfecto.' },
    ],
    aplicaciones: [
      { emoji: '🏆', titulo: 'Al hablar de logros', texto: 'Explicar lo que ya has conseguido.' },
      { emoji: '📚', titulo: 'En la escuela', texto: 'Presentar avances de un proyecto.' },
      { emoji: '🌎', titulo: 'En comunidad', texto: 'Contar acciones que siguen teniendo efecto.' },
    ],
  },
  'fase-5-just-already-yet': {
    slug: 'fase-5-just-already-yet', icono: '✅', zona: 'AVANCES DEL DÍA', titulo: 'Ya, recién y todavía',
    bajada: 'Usa already, just y yet para comunicar el avance de una tarea.', color: '#b06b33', suave: '#fff3e4', valor: 'Responsabilidad y comunicación honesta',
    historia: [
      { emoji: '📝', texto: 'I have already finished my homework.' },
      { emoji: '🎒', texto: 'My sister has just prepared her backpack.' },
      { emoji: '🧹', texto: 'We have already cleaned our room.' },
      { emoji: '🍽️', texto: 'My dad has not prepared dinner yet.' },
      { emoji: '🤝', texto: 'We check what is ready and help with what is still pending.' },
    ],
    palabras: [
      { en: 'already', es: 'ya', emoji: '✅' }, { en: 'just', es: 'recién/acabar de', emoji: '✨' },
      { en: 'yet', es: 'todavía/ya', emoji: '⏳' }, { en: 'finished', es: 'terminado', emoji: '🏁' },
      { en: 'prepared', es: 'preparado', emoji: '🎒' }, { en: 'pending', es: 'pendiente', emoji: '📌' },
    ],
    constructor: {
      inicios: ['I have already', 'We have just', 'She has already', 'He has just'],
      acciones: ['finished', 'started', 'checked', 'prepared'],
      finales: ['the homework.', 'the project.', 'the plan.', 'the materials.'],
    },
    retos: [
      { frase: 'I have ___ finished my homework.', correcta: 'already', opciones: ['yet', 'already', 'tomorrow'], ayuda: 'Already comunica que algo ya ocurrió.' },
      { frase: 'She has ___ arrived.', correcta: 'just', opciones: ['just', 'yet', 'ago'], ayuda: 'Just indica que ocurrió hace muy poco.' },
      { frase: 'Have you finished ___?', correcta: 'yet', opciones: ['already', 'just', 'yet'], ayuda: 'Yet suele ir al final de preguntas.' },
      { frase: 'We have not started ___.', correcta: 'yet', opciones: ['yet', 'just', 'yesterday'], ayuda: 'En una negación, yet significa todavía.' },
    ],
    aplicaciones: [
      { emoji: '📝', titulo: 'Con las tareas', texto: 'Informar qué terminaste y qué falta.' },
      { emoji: '👥', titulo: 'En equipo', texto: 'Coordinar avances sin repetir trabajo.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Comunicar responsabilidades cumplidas.' },
    ],
  },
  'fase-5-ever-how-long': {
    slug: 'fase-5-ever-how-long', icono: '🧭', zona: 'EXPERIENCIAS Y DURACIÓN', titulo: '¿Alguna vez? ¿Desde cuándo?',
    bajada: 'Pregunta por experiencias y por el tiempo que una situación ha continuado.', color: '#356f92', suave: '#e8f4fa', valor: 'Curiosidad y escucha respetuosa',
    historia: [
      { emoji: '🗣️', texto: 'Have you ever participated in a science fair?' },
      { emoji: '🔬', texto: 'Yes, I have. I enjoy building simple experiments.' },
      { emoji: '⏳', texto: 'How long have you studied science?' },
      { emoji: '📚', texto: 'I have studied it for three years.' },
      { emoji: '🤝', texto: 'We ask questions and listen carefully to each answer.' },
    ],
    palabras: [
      { en: 'ever', es: 'alguna vez', emoji: '❓' }, { en: 'never', es: 'nunca', emoji: '🚫' },
      { en: 'how long', es: 'desde hace cuánto', emoji: '⏳' }, { en: 'experience', es: 'experiencia', emoji: '🧭' },
      { en: 'for', es: 'durante/desde hace', emoji: '📏' }, { en: 'since', es: 'desde', emoji: '📍' },
    ],
    constructor: {
      inicios: ['Have you ever', 'Has she ever', 'How long have you', 'How long has he'],
      acciones: ['lived in', 'studied at', 'worked with', 'belonged to'],
      finales: ['this city?', 'this school?', 'that team?', 'the science club?'],
    },
    retos: [
      { frase: 'Have you ___ visited a museum?', correcta: 'ever', opciones: ['ever', 'ago', 'yet'], ayuda: 'Ever pregunta si ocurrió en algún momento.' },
      { frase: 'How ___ have you studied English?', correcta: 'long', opciones: ['many', 'long', 'old'], ayuda: 'How long pregunta por duración.' },
      { frase: 'I have ___ tried that activity.', correcta: 'never', opciones: ['never', 'last', 'ago'], ayuda: 'Never comunica que no ha ocurrido.' },
      { frase: 'She has studied here ___ two years.', correcta: 'for', opciones: ['since', 'ago', 'for'], ayuda: 'For acompaña una cantidad de tiempo.' },
    ],
    aplicaciones: [
      { emoji: '🤝', titulo: 'Al conocer personas', texto: 'Preguntar por experiencias con respeto.' },
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Hablar del tiempo en un curso o actividad.' },
      { emoji: '🎯', titulo: 'Al reflexionar', texto: 'Reconocer cuánto tiempo llevas aprendiendo.' },
    ],
  },
  'fase-5-for-since-ago': {
    slug: 'fase-5-for-since-ago', icono: '⏳', zona: 'MEDIR EL TIEMPO', titulo: 'Durante, desde y hace',
    bajada: 'Distingue for, since y ago según hables de duración, inicio o tiempo terminado.', color: '#735b9b', suave: '#f2edfb', valor: 'Precisión y constancia',
    historia: [
      { emoji: '🎹', texto: 'Emma has played the piano for three years.' },
      { emoji: '📅', texto: 'She has practiced at this school since 2023.' },
      { emoji: '🎵', texto: 'She joined the school group two years ago.' },
      { emoji: '⏱️', texto: 'For shows a duration, and since shows a starting point.' },
      { emoji: '⬅️', texto: 'Ago looks back from now to a finished past moment.' },
    ],
    palabras: [
      { en: 'for three years', es: 'durante tres años', emoji: '📏' }, { en: 'since Monday', es: 'desde el lunes', emoji: '📍' },
      { en: 'two days ago', es: 'hace dos días', emoji: '⬅️' }, { en: 'duration', es: 'duración', emoji: '⏳' },
      { en: 'starting point', es: 'punto de inicio', emoji: '🚩' }, { en: 'past moment', es: 'momento pasado', emoji: '🕰️' },
    ],
    constructor: {
      inicios: ['I compare', 'I identify', 'I explain', 'I check'],
      acciones: ['the duration in', 'the starting point in', 'the past time in', 'the time marker in'],
      finales: ['“for two weeks.”', '“since Monday.”', '“three days ago.”', '“since 2024.”'],
    },
    retos: [
      { frase: 'I have studied here ___ two years.', correcta: 'for', opciones: ['since', 'ago', 'for'], ayuda: 'Two years es una duración: usamos for.' },
      { frase: 'She has lived here ___ 2022.', correcta: 'since', opciones: ['for', 'since', 'ago'], ayuda: '2022 es el punto de inicio: usamos since.' },
      { frase: 'We started the project a week ___.', correcta: 'ago', opciones: ['for', 'since', 'ago'], ayuda: 'Ago cuenta hacia atrás desde ahora.' },
      { frase: 'They have practiced ___ Monday.', correcta: 'since', opciones: ['ago', 'for', 'since'], ayuda: 'Monday marca el inicio.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'Al hablar de estudios', texto: 'Decir cuánto tiempo llevas aprendiendo.' },
      { emoji: '🎨', titulo: 'En actividades', texto: 'Explicar cuándo comenzaste un pasatiempo.' },
      { emoji: '📖', titulo: 'Al contar hechos', texto: 'Ubicar un evento terminado en el pasado.' },
    ],
  },
  'fase-5-perfecto-vs-pasado': {
    slug: 'fase-5-perfecto-vs-pasado', icono: '⚖️', zona: 'EXPERIENCIA O FECHA', titulo: 'He vivido o viví',
    bajada: 'Elige entre presente perfecto y pasado simple según la información de tiempo.', color: '#39766a', suave: '#e8f7f2', valor: 'Pensamiento claro y comunicación precisa',
    historia: [
      { emoji: '🏕️', texto: 'I have visited a national park.' },
      { emoji: '📅', texto: 'I visited it last summer with my family.' },
      { emoji: '🌳', texto: 'We have learned many ways to protect nature.' },
      { emoji: '🗑️', texto: 'Last Saturday, we cleaned a trail near our town.' },
      { emoji: '🔎', texto: 'A specific finished time changes the tense we choose.' },
    ],
    palabras: [
      { en: 'I have visited', es: 'he visitado', emoji: '🧭' }, { en: 'I visited', es: 'visité', emoji: '📅' },
      { en: 'ever', es: 'alguna vez', emoji: '❓' }, { en: 'last year', es: 'el año pasado', emoji: '⬅️' },
      { en: 'experience', es: 'experiencia', emoji: '⭐' }, { en: 'specific time', es: 'tiempo específico', emoji: '📌' },
    ],
    constructor: {
      inicios: ['I compare', 'I identify', 'I explain', 'I check'],
      acciones: ['the experience in', 'the finished time in', 'the verb form in', 'the time marker in'],
      finales: ['“I have visited a park.”', '“I visited it last year.”', '“She has finished.”', '“She finished yesterday.”'],
    },
    retos: [
      { frase: 'I ___ that museum last year.', correcta: 'visited', opciones: ['have visited', 'visited', 'visit'], ayuda: 'Last year es un tiempo pasado terminado.' },
      { frase: 'I have ___ a science fair.', correcta: 'attended', opciones: ['attend', 'attended', 'attending'], ayuda: 'Sin fecha específica, expresamos la experiencia.' },
      { frase: 'She ___ her homework yesterday.', correcta: 'finished', opciones: ['has finished', 'finished', 'finishes'], ayuda: 'Yesterday requiere pasado simple.' },
      { frase: 'We have ___ many useful skills.', correcta: 'learned', opciones: ['learn', 'learned', 'learning'], ayuda: 'Have + learned conecta el aprendizaje con hoy.' },
    ],
    aplicaciones: [
      { emoji: '💬', titulo: 'En conversación', texto: 'Compartir una experiencia y después precisar cuándo.' },
      { emoji: '📝', titulo: 'Al escribir', texto: 'Mantener clara la línea de tiempo de una historia.' },
      { emoji: '🏫', titulo: 'En proyectos', texto: 'Diferenciar logros actuales y acciones fechadas.' },
    ],
  },
  'fase-6-pasiva-presente': {
    slug: 'fase-6-pasiva-presente', icono: '♻️', zona: 'CÓMO SE HACEN LAS COSAS', titulo: 'Así se cuida nuestra escuela',
    bajada: 'Usa la voz pasiva para destacar una acción o su resultado en el presente.', color: '#31865b', suave: '#e5f8ed', valor: 'Cuidado compartido y responsabilidad',
    historia: [
      { emoji: '📄', texto: 'Paper is collected in every classroom.' },
      { emoji: '♻️', texto: 'Useful sheets are reused for notes.' },
      { emoji: '🧴', texto: 'Plastic is separated from other waste.' },
      { emoji: '🌱', texto: 'The garden is watered with collected rainwater.' },
      { emoji: '🏫', texto: 'Our school is cared for by the whole community.' },
    ],
    palabras: [
      { en: 'is collected', es: 'es recolectado', emoji: '📦' }, { en: 'are reused', es: 'son reutilizados', emoji: '♻️' },
      { en: 'is separated', es: 'es separado', emoji: '🗂️' }, { en: 'is watered', es: 'es regado', emoji: '💧' },
      { en: 'by', es: 'por', emoji: '👥' }, { en: 'result', es: 'resultado', emoji: '✅' },
    ],
    constructor: {
      inicios: ['Paper is', 'Plastic is', 'Glass is', 'Old notebooks are'],
      acciones: ['collected', 'reused', 'separated', 'stored'],
      finales: ['in our classroom.', 'by the students.', 'for another activity.', 'with care.'],
    },
    retos: [
      { frase: 'Paper ___ collected at school.', correcta: 'is', opciones: ['are', 'is', 'was'], ayuda: 'Paper es singular y la acción es presente.' },
      { frase: 'The bottles are ___.', correcta: 'reused', opciones: ['reuse', 'reused', 'reusing'], ayuda: 'La pasiva usa be + participio: are reused.' },
      { frase: 'The garden is watered ___ the students.', correcta: 'by', opciones: ['at', 'by', 'on'], ayuda: 'By introduce quién realiza la acción.' },
      { frase: 'Old notebooks ___ stored safely.', correcta: 'are', opciones: ['is', 'are', 'was'], ayuda: 'Notebooks es plural: usamos are.' },
    ],
    aplicaciones: [
      { emoji: '🔬', titulo: 'Al explicar procesos', texto: 'Describir cómo se realiza una actividad.' },
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Destacar resultados y normas compartidas.' },
      { emoji: '♻️', titulo: 'Al cuidar el ambiente', texto: 'Explicar cómo se separan y reutilizan materiales.' },
    ],
  },
  'fase-6-pasiva-pasado': {
    slug: 'fase-6-pasiva-pasado', icono: '🏗️', zona: 'RESULTADOS DEL PASADO', titulo: 'Así fue creado',
    bajada: 'Usa was o were más participio para explicar cómo se obtuvo un resultado pasado.', color: '#356f92', suave: '#e8f4fa', valor: 'Reconocer el trabajo de los demás',
    historia: [
      { emoji: '🌳', texto: 'A new reading corner was created at our school.' },
      { emoji: '📚', texto: 'The books were donated by local families.' },
      { emoji: '🎨', texto: 'The signs were painted by the art class.' },
      { emoji: '🪑', texto: 'The old chairs were repaired and reused.' },
      { emoji: '🤝', texto: 'The space was opened last Friday for everyone.' },
    ],
    palabras: [
      { en: 'was created', es: 'fue creado', emoji: '🏗️' }, { en: 'were donated', es: 'fueron donados', emoji: '🎁' },
      { en: 'were painted', es: 'fueron pintados', emoji: '🎨' }, { en: 'were repaired', es: 'fueron reparados', emoji: '🛠️' },
      { en: 'was opened', es: 'fue inaugurado', emoji: '🚪' }, { en: 'by', es: 'por', emoji: '👥' },
    ],
    constructor: {
      inicios: ['The poster was', 'The garden was', 'The boxes were', 'The materials were'],
      acciones: ['created', 'prepared', 'painted', 'organized'],
      finales: ['by our class.', 'last week.', 'for the event.', 'with care.'],
    },
    retos: [
      { frase: 'The corner ___ created last month.', correcta: 'was', opciones: ['is', 'were', 'was'], ayuda: 'Corner es singular y la acción ocurrió en el pasado.' },
      { frase: 'The books ___ donated by families.', correcta: 'were', opciones: ['was', 'were', 'are'], ayuda: 'Books es plural: usamos were.' },
      { frase: 'The chairs were ___.', correcta: 'repaired', opciones: ['repair', 'repaired', 'repairing'], ayuda: 'La pasiva requiere el participio repaired.' },
      { frase: 'The signs were painted ___ the students.', correcta: 'by', opciones: ['by', 'on', 'at'], ayuda: 'By presenta a quienes realizaron la acción.' },
    ],
    aplicaciones: [
      { emoji: '📖', titulo: 'Al contar una historia', texto: 'Explicar cómo se creó algo en el pasado.' },
      { emoji: '🏫', titulo: 'En proyectos', texto: 'Reconocer quién realizó cada contribución.' },
      { emoji: '🛠️', titulo: 'Al describir resultados', texto: 'Centrarte en lo construido, reparado o preparado.' },
    ],
  },
  'fase-7-going-to': {
    slug: 'fase-7-going-to', icono: '🧭', zona: 'PLANES CON INTENCIÓN', titulo: 'Lo que voy a hacer',
    bajada: 'Usa going to para expresar una intención o un plan decidido.', color: '#356f92', suave: '#e8f4fa', valor: 'Organización y compromiso',
    historia: [
      { emoji: '📅', texto: 'This weekend, my family is going to visit my grandparents.' },
      { emoji: '🥗', texto: 'My mom is going to prepare a healthy lunch.' },
      { emoji: '🌱', texto: 'My dad and I are going to work in the garden.' },
      { emoji: '📚', texto: 'My sister is going to bring a book for Grandma.' },
      { emoji: '🤝', texto: 'We are going to enjoy our time and help with the chores.' },
    ],
    palabras: [
      { en: 'plan', es: 'plan', emoji: '📋' }, { en: 'intention', es: 'intención', emoji: '🎯' },
      { en: 'going to', es: 'ir a', emoji: '➡️' }, { en: 'this weekend', es: 'este fin de semana', emoji: '📅' },
      { en: 'prepare', es: 'preparar', emoji: '🎒' }, { en: 'visit', es: 'visitar', emoji: '🏠' },
    ],
    constructor: {
      inicios: ['Tomorrow, I am', 'This weekend, we are', 'After school, she is', 'On Saturday, he is'],
      acciones: ['going to study', 'going to visit', 'going to help', 'going to prepare'],
      finales: ['after lunch.', 'with the family.', 'for the activity.', 'at home.'],
    },
    retos: [
      { frase: 'I am ___ to study tonight.', correcta: 'going', opciones: ['go', 'going', 'went'], ayuda: 'La estructura es am/is/are + going to.' },
      { frase: 'She ___ going to help her mom.', correcta: 'is', opciones: ['am', 'are', 'is'], ayuda: 'Con she usamos is going to.' },
      { frase: 'We are going to ___ our grandparents.', correcta: 'visit', opciones: ['visited', 'visiting', 'visit'], ayuda: 'Después de going to usamos el verbo base.' },
      { frase: 'They ___ going to prepare lunch.', correcta: 'are', opciones: ['is', 'are', 'am'], ayuda: 'Con they usamos are.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'Al estudiar', texto: 'Explicar qué tarea o proyecto planeas hacer.' },
      { emoji: '🏠', titulo: 'En familia', texto: 'Organizar visitas y responsabilidades.' },
      { emoji: '🌱', titulo: 'En actividades', texto: 'Comunicar una intención antes de comenzar.' },
    ],
  },
  'fase-7-will-shall': {
    slug: 'fase-7-will-shall', icono: '🚀', zona: 'PLANES Y RESPONSABILIDAD', titulo: 'Mis planes para mañana',
    bajada: 'Usa will para expresar decisiones, promesas y acciones futuras.', color: '#735b9b', suave: '#f2edfb', valor: 'Responsabilidad y cumplimiento',
    historia: [
      { emoji: '🌅', texto: 'Tomorrow will be a busy day for Alex.' },
      { emoji: '📝', texto: 'I will do my homework after school.' },
      { emoji: '🌱', texto: 'Then I will help my dad water the plants.' },
      { emoji: '📞', texto: 'I will call my grandparents in the evening.' },
      { emoji: '⭐', texto: 'I will keep my promises and do my best.' },
    ],
    palabras: [
      { en: 'tomorrow', es: 'mañana', emoji: '🌅' }, { en: 'homework', es: 'tarea', emoji: '📝' },
      { en: 'promise', es: 'promesa', emoji: '🤝' }, { en: 'help', es: 'ayudar', emoji: '🙌' },
      { en: 'later', es: 'más tarde', emoji: '🕒' }, { en: 'will', es: 'acción futura', emoji: '➡️' },
    ],
    constructor: {
      inicios: ['Tomorrow, I', 'After school, I', 'This weekend, I', 'Later, I'],
      acciones: ['will start', 'will finish', 'will organize', 'will review'],
      finales: ['my homework.', 'my chores.', 'my plan.', 'my project.'],
    },
    retos: [
      { frase: 'Tomorrow I ___ do my homework.', correcta: 'will', opciones: ['will', 'am', 'did'], ayuda: 'Will + verbo expresa una acción futura.' },
      { frase: 'She will ___ her mom after school.', correcta: 'help', opciones: ['helps', 'help', 'helped'], ayuda: 'Después de will usamos el verbo sin cambios.' },
      { frase: 'We ___ visit our grandparents on Sunday.', correcta: 'will', opciones: ['are', 'will', 'were'], ayuda: 'Will presenta el plan futuro.' },
      { frase: 'I will keep my ___.', correcta: 'promise', opciones: ['promise', 'promised', 'promising'], ayuda: 'Keep my promise significa cumplir mi promesa.' },
    ],
    aplicaciones: [
      { emoji: '📚', titulo: 'Tareas', texto: 'Explicar qué harás después de clases.' },
      { emoji: '📅', titulo: 'Planes', texto: 'Organizar actividades para mañana.' },
      { emoji: '🤝', titulo: 'Compromisos', texto: 'Expresar una promesa y cumplirla.' },
    ],
  },
  'fase-7-continuo-futuro': {
    slug: 'fase-7-continuo-futuro', icono: '📆', zona: 'ACUERDOS ORGANIZADOS', titulo: 'Mi agenda ya está lista',
    bajada: 'Usa el presente continuo para planes futuros que ya tienen un acuerdo.', color: '#39766a', suave: '#e8f7f2', valor: 'Puntualidad y respeto por los acuerdos',
    historia: [
      { emoji: '🔬', texto: 'Our science group is meeting tomorrow at four.' },
      { emoji: '📚', texto: 'We are working in the school library.' },
      { emoji: '👩‍🏫', texto: 'Our teacher is joining us after class.' },
      { emoji: '🧪', texto: 'Sofia is bringing the experiment materials.' },
      { emoji: '📅', texto: 'The time and place are confirmed, so the plan is arranged.' },
    ],
    palabras: [
      { en: 'arrangement', es: 'acuerdo organizado', emoji: '🤝' }, { en: 'meeting', es: 'reuniéndose', emoji: '👥' },
      { en: 'tomorrow', es: 'mañana', emoji: '➡️' }, { en: 'confirmed', es: 'confirmado', emoji: '✅' },
      { en: 'time', es: 'hora', emoji: '🕓' }, { en: 'place', es: 'lugar', emoji: '📍' },
    ],
    constructor: {
      inicios: ['Tomorrow, I am', 'On Friday, we are', 'After class, she is', 'This evening, they are'],
      acciones: ['meeting', 'visiting', 'studying with', 'working with'],
      finales: ['my classmates.', 'our grandparents.', 'the school group.', 'our teacher.'],
    },
    retos: [
      { frase: 'We are ___ tomorrow at four.', correcta: 'meeting', opciones: ['meet', 'meeting', 'met'], ayuda: 'Are + meeting expresa un acuerdo futuro.' },
      { frase: 'She ___ visiting Grandma on Sunday.', correcta: 'is', opciones: ['is', 'are', 'was'], ayuda: 'Con she usamos is.' },
      { frase: 'I am studying ___ Leo tonight.', correcta: 'with', opciones: ['at', 'with', 'on'], ayuda: 'With indica con quién está organizado el plan.' },
      { frase: 'They are ___ the materials tomorrow.', correcta: 'bringing', opciones: ['bring', 'brought', 'bringing'], ayuda: 'Are + bringing presenta el acuerdo futuro.' },
    ],
    aplicaciones: [
      { emoji: '👥', titulo: 'En trabajos de equipo', texto: 'Confirmar con quién te reunirás.' },
      { emoji: '📅', titulo: 'En tu agenda', texto: 'Explicar planes con hora o lugar definidos.' },
      { emoji: '🏠', titulo: 'En familia', texto: 'Comunicar visitas y actividades acordadas.' },
    ],
  },
  'fase-16-condicionales-if': {
    slug: 'fase-16-condicionales-if', icono: '🌎', zona: 'GUARDIANES DE LA NATURALEZA', titulo: 'Si cuidamos, protegemos',
    bajada: 'Conecta una acción responsable con su resultado usando if.', color: '#31865b', suave: '#e5f8ed', valor: 'Respeto y cuidado del medio ambiente',
    historia: [
      { emoji: '🏫', texto: 'Our class has a plan to care for the environment.' },
      { emoji: '💧', texto: 'If we turn off the tap, we save water.' },
      { emoji: '📄', texto: 'If we reuse paper, we protect trees.' },
      { emoji: '🗑️', texto: 'If we pick up litter, our park stays clean.' },
      { emoji: '🌳', texto: 'Small actions can make a big difference.' },
    ],
    palabras: [
      { en: 'save water', es: 'ahorrar agua', emoji: '💧' }, { en: 'reuse', es: 'reutilizar', emoji: '♻️' },
      { en: 'protect', es: 'proteger', emoji: '🛡️' }, { en: 'trees', es: 'árboles', emoji: '🌳' },
      { en: 'clean', es: 'limpio', emoji: '✨' }, { en: 'environment', es: 'medio ambiente', emoji: '🌎' },
    ],
    constructor: {
      inicios: ['If we save water,', 'If we reuse paper,', 'If we care for animals,', 'If we pick up litter,'],
      acciones: ['we help protect', 'we take care of', 'we support', 'we make a difference for'],
      finales: ['our planet.', 'nature.', 'our community.', 'the world around us.'],
    },
    retos: [
      { frase: 'If we reuse paper, we ___ trees.', correcta: 'protect', opciones: ['protect', 'waste', 'cut'], ayuda: 'Reutilizar papel ayuda a proteger árboles.' },
      { frase: 'If you turn off the tap, you ___ water.', correcta: 'save', opciones: ['drop', 'save', 'lose'], ayuda: 'Save water significa ahorrar agua.' },
      { frase: 'If we ___ litter, the park stays clean.', correcta: 'pick up', opciones: ['leave', 'drop', 'pick up'], ayuda: 'Pick up litter significa recoger basura.' },
      { frase: 'If we care for nature, we ___ our home.', correcta: 'protect', opciones: ['protect', 'forget', 'waste'], ayuda: 'El planeta es nuestro hogar compartido.' },
    ],
    aplicaciones: [
      { emoji: '🏫', titulo: 'En la escuela', texto: 'Proponer acciones para un salón limpio.' },
      { emoji: '🏠', titulo: 'En casa', texto: 'Explicar cómo ahorrar agua y reutilizar.' },
      { emoji: '🌳', titulo: 'En comunidad', texto: 'Invitar a otros a cuidar parques y árboles.' },
    ],
  },
};

export const CHILD_MISSION_SLUGS = new Set(Object.keys(CHILD_MISSIONS));
